use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const HOST_SHARE_DIR: &str = "host_shared";
const HOST_SHARE_MAX_FILE_BYTES: u64 = 4 * 1024 * 1024;

#[derive(Debug)]
struct SnapshotFile {
    relative: String,
    absolute: PathBuf,
    len: u64,
}

#[derive(Debug)]
struct SkippedFile {
    relative: String,
    reason: &'static str,
    len: u64,
}

fn rust_string_literal(value: &str) -> String {
    format!("{value:?}")
}

fn relative_string(path: &Path) -> Option<String> {
    let text = path.to_str()?;
    if text.is_empty() || text.starts_with('/') || text.contains("//") {
        return None;
    }
    for part in text.split('/') {
        if part.is_empty() || part == "." || part == ".." {
            return None;
        }
    }
    Some(text.replace('\\', "/"))
}

fn collect_snapshot(
    root: &Path,
    dir: &Path,
    files: &mut Vec<SnapshotFile>,
    dirs: &mut Vec<String>,
    skipped: &mut Vec<SkippedFile>,
) {
    println!("cargo:rerun-if-changed={}", dir.display());

    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        println!("cargo:rerun-if-changed={}", path.display());

        let Ok(metadata) = entry.metadata() else {
            continue;
        };
        let Ok(relative_path) = path.strip_prefix(root) else {
            continue;
        };
        let Some(relative) = relative_string(relative_path) else {
            continue;
        };

        if metadata.is_dir() {
            dirs.push(relative);
            collect_snapshot(root, &path, files, dirs, skipped);
        } else if metadata.is_file() {
            if metadata.len() > HOST_SHARE_MAX_FILE_BYTES {
                skipped.push(SkippedFile {
                    relative,
                    reason: "too-large",
                    len: metadata.len(),
                });
            } else {
                files.push(SnapshotFile {
                    relative,
                    absolute: path,
                    len: metadata.len(),
                });
            }
        }
    }
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let host_share_root = manifest_dir.join(HOST_SHARE_DIR);
    println!("cargo:rerun-if-changed={}", host_share_root.display());

    let mut dirs = Vec::new();
    let mut files = Vec::new();
    let mut skipped = Vec::new();
    if host_share_root.is_dir() {
        collect_snapshot(
            &host_share_root,
            &host_share_root,
            &mut files,
            &mut dirs,
            &mut skipped,
        );
    }

    dirs.sort();
    dirs.dedup();
    files.sort_by(|a, b| a.relative.cmp(&b.relative));
    skipped.sort_by(|a, b| a.relative.cmp(&b.relative));

    let mut generated = String::new();
    generated.push_str("// Generated by build.rs from host_shared/. Do not edit.\n");
    generated.push_str("#[derive(Clone, Copy, Debug)]\n");
    generated.push_str("pub struct HostShareFile {\n");
    generated.push_str("    pub path: &'static str,\n");
    generated.push_str("    pub data: &'static [u8],\n");
    generated.push_str("}\n\n");
    generated.push_str("#[derive(Clone, Copy, Debug)]\n");
    generated.push_str("pub struct HostShareSkipped {\n");
    generated.push_str("    pub path: &'static str,\n");
    generated.push_str("    pub reason: &'static str,\n");
    generated.push_str("    pub size: usize,\n");
    generated.push_str("}\n\n");
    generated.push_str("pub const HOST_SHARE_ROOT: &str = \"host_shared\";\n");
    generated.push_str(&format!(
        "pub const HOST_SHARE_MAX_FILE_BYTES: usize = {};\n",
        HOST_SHARE_MAX_FILE_BYTES
    ));
    generated.push_str("pub static HOST_SHARE_DIRS: &[&str] = &[\n");
    for dir in &dirs {
        generated.push_str("    ");
        generated.push_str(&rust_string_literal(dir));
        generated.push_str(",\n");
    }
    generated.push_str("];\n\n");
    generated.push_str("pub static HOST_SHARE_FILES: &[HostShareFile] = &[\n");
    for file in &files {
        let absolute = file.absolute.to_string_lossy();
        generated.push_str("    HostShareFile { path: ");
        generated.push_str(&rust_string_literal(&file.relative));
        generated.push_str(", data: include_bytes!(");
        generated.push_str(&rust_string_literal(&absolute));
        generated.push_str(") },\n");
        println!(
            "cargo:warning=host_shared include {} ({} bytes)",
            file.relative, file.len
        );
    }
    generated.push_str("];\n\n");
    generated.push_str("pub static HOST_SHARE_SKIPPED: &[HostShareSkipped] = &[\n");
    for file in &skipped {
        generated.push_str("    HostShareSkipped { path: ");
        generated.push_str(&rust_string_literal(&file.relative));
        generated.push_str(", reason: ");
        generated.push_str(&rust_string_literal(file.reason));
        generated.push_str(", size: ");
        generated.push_str(&file.len.to_string());
        generated.push_str(" },\n");
        println!(
            "cargo:warning=host_shared skip {}: {} ({} bytes)",
            file.relative, file.reason, file.len
        );
    }
    generated.push_str("];\n");

    fs::write(out_dir.join("host_share.rs"), generated).unwrap();
}
