#![allow(dead_code)]
#![allow(static_mut_refs)]
//! Zircon port kernel object.
//!
//! Ports queue fixed-size packets. User packets are copied in by
//! `zx_port_queue`; signal packets are generated by `zx_object_wait_async`.

use super::{object_logic, port_logic, HandleValue, ZxError, ZxResult, INVALID_HANDLE};

const PORT_HANDLE_START: u32 = 0x9200_0000;
const MAX_PORT_OBJECTS: usize = 16;
const MAX_PORT_PACKETS: usize = 32;
const MAX_PORT_OBSERVERS: usize = 32;
const PORT_CREATE_OPTIONS_MASK: u32 = 0;
const PORT_USER_PACKET_SOURCE: HandleValue = HandleValue(INVALID_HANDLE);

pub const PORT_PACKET_TYPE_USER: u32 = 0;
pub const PORT_PACKET_TYPE_SIGNAL_ONE: u32 = 1;
pub const PORT_PACKET_SIZE: usize = core::mem::size_of::<PortPacket>();
pub const WAIT_ASYNC_TIMESTAMP: u32 = 1 << 0;
pub const WAIT_ASYNC_BOOT_TIMESTAMP: u32 = 1 << 1;
pub const WAIT_ASYNC_EDGE: u32 = 1 << 2;
pub const WAIT_ASYNC_OPTIONS_MASK: u32 =
    WAIT_ASYNC_TIMESTAMP | WAIT_ASYNC_BOOT_TIMESTAMP | WAIT_ASYNC_EDGE;

#[repr(C)]
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct PortPacket {
    pub key: u64,
    pub packet_type: u32,
    pub status: i32,
    pub data0: u64,
    pub data1: u64,
    pub data2: u64,
    pub data3: u64,
}

impl PortPacket {
    pub const fn empty() -> Self {
        Self {
            key: 0,
            packet_type: 0,
            status: 0,
            data0: 0,
            data1: 0,
            data2: 0,
            data3: 0,
        }
    }

    pub fn signal(key: u64, observed: u32, trigger: u32, count: u64) -> Self {
        Self {
            key,
            packet_type: PORT_PACKET_TYPE_SIGNAL_ONE,
            status: 0,
            data0: trigger as u64,
            data1: observed as u64,
            data2: count,
            data3: 0,
        }
    }
}

#[derive(Clone, Copy)]
struct PortObserver {
    source: HandleValue,
    key: u64,
    signals: u32,
    options: u32,
    last_observed: u32,
    active: bool,
}

impl PortObserver {
    const fn empty() -> Self {
        Self {
            source: HandleValue(INVALID_HANDLE),
            key: 0,
            signals: 0,
            options: 0,
            last_observed: 0,
            active: false,
        }
    }
}

#[derive(Clone, Copy)]
struct PortObject {
    handle: HandleValue,
    packets: [PortPacket; MAX_PORT_PACKETS],
    packet_sources: [HandleValue; MAX_PORT_PACKETS],
    observers: [PortObserver; MAX_PORT_OBSERVERS],
    head: usize,
    len: usize,
    signals: u32,
    active: bool,
}

impl PortObject {
    pub const fn empty() -> Self {
        Self {
            handle: HandleValue(INVALID_HANDLE),
            packets: [PortPacket::empty(); MAX_PORT_PACKETS],
            packet_sources: [PORT_USER_PACKET_SOURCE; MAX_PORT_PACKETS],
            observers: [PortObserver::empty(); MAX_PORT_OBSERVERS],
            head: 0,
            len: 0,
            signals: 0,
            active: false,
        }
    }

    fn activate(&mut self, handle: HandleValue) {
        self.handle = handle;
        self.packets = [PortPacket::empty(); MAX_PORT_PACKETS];
        self.packet_sources = [PORT_USER_PACKET_SOURCE; MAX_PORT_PACKETS];
        self.observers = [PortObserver::empty(); MAX_PORT_OBSERVERS];
        self.head = 0;
        self.len = 0;
        self.signals = 0;
        self.active = true;
    }

    fn clear(&mut self) {
        self.handle = HandleValue(INVALID_HANDLE);
        self.packets = [PortPacket::empty(); MAX_PORT_PACKETS];
        self.packet_sources = [PORT_USER_PACKET_SOURCE; MAX_PORT_PACKETS];
        self.observers = [PortObserver::empty(); MAX_PORT_OBSERVERS];
        self.head = 0;
        self.len = 0;
        self.signals = 0;
        self.active = false;
    }

    fn tail(&self) -> usize {
        (self.head + self.len) % MAX_PORT_PACKETS
    }

    fn refresh_readable_signal(&mut self) {
        if self.len == 0 {
            self.signals &= !crate::kernel_objects::channel::CHANNEL_SIGNAL_READABLE;
        } else {
            self.signals |= crate::kernel_objects::channel::CHANNEL_SIGNAL_READABLE;
        }
    }

    fn push(&mut self, packet: PortPacket, source: HandleValue) -> ZxResult {
        if !port_logic::queue_has_space(self.len, MAX_PORT_PACKETS) {
            return Err(ZxError::ErrShouldWait);
        }
        let tail = self.tail();
        self.packets[tail] = packet;
        self.packet_sources[tail] = source;
        self.len += 1;
        self.refresh_readable_signal();
        Ok(())
    }

    fn pop(&mut self) -> Option<PortPacket> {
        if self.len == 0 {
            return None;
        }
        let packet = self.packets[self.head];
        self.packets[self.head] = PortPacket::empty();
        self.packet_sources[self.head] = PORT_USER_PACKET_SOURCE;
        self.head = (self.head + 1) % MAX_PORT_PACKETS;
        self.len -= 1;
        if self.len == 0 {
            self.head = 0;
        }
        self.refresh_readable_signal();
        Some(packet)
    }

    fn observer_index(&self, source: HandleValue, key: u64) -> Option<usize> {
        self.observers.iter().position(|observer| {
            observer.active && observer.source == source && observer.key == key
        })
    }

    fn free_observer_index(&self) -> Option<usize> {
        self.observers.iter().position(|observer| !observer.active)
    }

    fn register_observer(
        &mut self,
        source: HandleValue,
        key: u64,
        observed: u32,
        signals: u32,
        options: u32,
    ) -> ZxResult {
        let observer_index = match self.observer_index(source, key) {
            Some(index) => index,
            None => self.free_observer_index().ok_or(ZxError::ErrNoMemory)?,
        };

        self.observers[observer_index] = PortObserver {
            source,
            key,
            signals,
            options,
            last_observed: observed,
            active: true,
        };
        Ok(())
    }

    fn compact_without(&mut self, source: HandleValue, key: u64) -> u32 {
        let mut compact_packets = [PortPacket::empty(); MAX_PORT_PACKETS];
        let mut compact_sources = [PORT_USER_PACKET_SOURCE; MAX_PORT_PACKETS];
        let mut kept = 0usize;
        let mut removed = 0u32;

        for offset in 0..self.len {
            let packet_index = (self.head + offset) % MAX_PORT_PACKETS;
            let packet = self.packets[packet_index];
            let packet_source = self.packet_sources[packet_index];
            if packet.key == key && packet_source == source {
                removed = removed.saturating_add(1);
            } else {
                compact_packets[kept] = packet;
                compact_sources[kept] = packet_source;
                kept += 1;
            }
        }

        self.packets = compact_packets;
        self.packet_sources = compact_sources;
        self.head = 0;
        self.len = kept;
        self.refresh_readable_signal();
        removed
    }
}

pub struct PortTable {
    ports: [PortObject; MAX_PORT_OBJECTS],
    next_handle: u32,
}

impl PortTable {
    pub const fn new() -> Self {
        Self {
            ports: [PortObject::empty(); MAX_PORT_OBJECTS],
            next_handle: PORT_HANDLE_START,
        }
    }

    fn alloc_handle(&mut self) -> Option<HandleValue> {
        if self.next_handle == INVALID_HANDLE {
            return None;
        }

        let handle = self.next_handle;
        self.next_handle = self.next_handle.checked_add(1)?;

        if object_logic::handle_is_valid(handle, INVALID_HANDLE) {
            Some(HandleValue(handle))
        } else {
            None
        }
    }

    fn index(&self, handle: HandleValue) -> Option<usize> {
        self.ports
            .iter()
            .position(|port| port.active && port.handle == handle)
    }

    fn free_index(&self) -> Option<usize> {
        self.ports.iter().position(|port| !port.active)
    }

    pub fn contains(&self, handle: HandleValue) -> bool {
        self.index(handle).is_some()
    }

    pub fn create(&mut self, options: u32) -> ZxResult<HandleValue> {
        if !port_logic::options_valid(options, PORT_CREATE_OPTIONS_MASK) {
            return Err(ZxError::ErrInvalidArgs);
        }
        let index = self.free_index().ok_or(ZxError::ErrNoMemory)?;
        let handle = self.alloc_handle().ok_or(ZxError::ErrNoMemory)?;
        self.ports[index].activate(handle);
        Ok(handle)
    }

    pub fn close(&mut self, handle: HandleValue) -> bool {
        let Some(index) = self.index(handle) else {
            return false;
        };
        self.ports[index].clear();
        true
    }

    pub fn signals(&self, handle: HandleValue) -> Option<u32> {
        self.index(handle).map(|index| self.ports[index].signals)
    }

    pub fn update_signals(
        &mut self,
        handle: HandleValue,
        clear_mask: u32,
        set_mask: u32,
    ) -> Option<u32> {
        let index = self.index(handle)?;
        self.ports[index].signals =
            object_logic::signal_update(self.ports[index].signals, clear_mask, set_mask);
        Some(self.ports[index].signals)
    }

    pub fn queue(&mut self, handle: HandleValue, packet: PortPacket) -> ZxResult {
        let index = self.index(handle).ok_or(ZxError::ErrNotFound)?;
        self.ports[index].push(packet, PORT_USER_PACKET_SOURCE)
    }

    pub fn wait(&mut self, handle: HandleValue, deadline: u64) -> ZxResult<PortPacket> {
        let index = self.index(handle).ok_or(ZxError::ErrNotFound)?;
        if let Some(packet) = self.ports[index].pop() {
            Ok(packet)
        } else if deadline == 0 {
            Err(ZxError::ErrTimedOut)
        } else {
            Err(ZxError::ErrShouldWait)
        }
    }

    pub fn cancel(&mut self, handle: HandleValue, source: HandleValue, key: u64) -> ZxResult<u32> {
        let index = self.index(handle).ok_or(ZxError::ErrNotFound)?;
        let mut removed = self.ports[index].compact_without(source, key);

        for observer in &mut self.ports[index].observers {
            if observer.active && observer.source == source && observer.key == key {
                observer.active = false;
                removed = removed.saturating_add(1);
            }
        }

        Ok(removed)
    }

    pub fn queue_signal(
        &mut self,
        port: HandleValue,
        source: HandleValue,
        key: u64,
        observed: u32,
        signals: u32,
        options: u32,
    ) -> ZxResult<bool> {
        let index = self.index(port).ok_or(ZxError::ErrNotFound)?;
        self.ports[index].register_observer(source, key, observed, signals, options)?;
        if !port_logic::signal_packet_allowed(observed, signals) {
            return Ok(false);
        }
        let packet = PortPacket::signal(key, observed, signals, 1);
        self.ports[index].push(packet, source)?;
        Ok(true)
    }

    pub fn notify_signal(&mut self, source: HandleValue, observed: u32) {
        for port_index in 0..self.ports.len() {
            if !self.ports[port_index].active {
                continue;
            }

            for observer_index in 0..self.ports[port_index].observers.len() {
                let observer = self.ports[port_index].observers[observer_index];
                if !observer.active || observer.source != source {
                    continue;
                }

                let edge = observer.options & WAIT_ASYNC_EDGE != 0;
                if port_logic::observer_should_queue(
                    observer.last_observed,
                    observed,
                    observer.signals,
                    edge,
                ) {
                    let packet = PortPacket::signal(observer.key, observed, observer.signals, 1);
                    if self.ports[port_index].push(packet, source).is_err() {
                        self.ports[port_index].observers[observer_index].active = false;
                    }
                }
                self.ports[port_index].observers[observer_index].last_observed = observed;
            }
        }
    }
}

static mut PORT_TABLE: PortTable = PortTable::new();

pub fn port_table() -> &'static mut PortTable {
    unsafe { &mut PORT_TABLE }
}
